apiVersion: v1
kind: Pod
metadata:   #실제 데이터에 대한 요약 정보, 추가 정보, 메타데이터를 통해 실제 데이터를 찾을 수 있다.
  name: myapp  #pod 이름
  labels:
    name: myapp
spec:
  containers:
  - name: myapp   #첫번째 컨테이너
    image: nginx   #컨테이너 이미지
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m" #1000m을 1개로 본다.  여기서는 500이니까 0.5개를 사용하는 것이다.
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
