apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: keduit-rs
  labels:
    app: myapp
    key: value
spec:
  replicas: 3
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
        - name: keduit-ctn
          image: jiho9898/keduinitlab:blue
          ports:
          - containerPort: 80
