apiVersion: v1
kind: Service
metadata:
  name: keduit-svc1
spec:
  selector:
    color: blue
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  # 'nodePort'의 P는 대문자로 표기해야 함
  type: NodePort
