apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      color: blue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
      - name: myapp
        image: jiho9898/portal:shop
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 80